name = "rank-overlay"
type = "javascript"
compatibility_date = "2022-05-05"

zone_id = ""
account_id = ""
route = ""
workers_dev = true

[site]
bucket = "./public"
entry-point = "."

[build]
command = "npm run build"

[build.upload]
format="service-worker"

